# -*- coding: utf-8 -*-
"""APE 2022.1 - Lista Resolvida - Strings.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QiRkZe6dIsVLzxrEhseVb0PWKXtioWSg

**IFPB - CAMPUS JOÃO PESSOA    
CURSO: SISTEMAS PARA INTERNET     
DISCIPLINA: ALGORITMOS E PROGRAMAÇÃO ESTRUTURADA     
PROFESSORES: CANDIDO EGYPTO / EDEMBERG ROCHA**

# LISTA DE EXERCÍCIOS (RESOLVIDA) - STRINGS

##Questão 1

Faça um programa que leia uma frase e determine a quantidade de brancos contidos na mesma.
"""

frase = input('Frase: ')

n = frase.count(' ')

print(f'A frase contém {n} brancos')

#Versão sem o uso de count()

frase = input('Frase: ')

n = 0
for caracter in frase:
    if caracter == ' ':
        n += 1    

print(f'A frase contém {n} brancos')

"""##Questão 2

Faça um programa que leia uma frase e a exiba sem os espaços em branco.
"""

frase = input('Frase: ')

saida = frase.replace(' ','')

print(saida)

#Versão sem o uso de replace()

frase = input('Frase: ')

for caracter in frase:
    if caracter != ' ':
        print(caracter,end='')

#Outra versão sem o uso de replace()

frase = input('Frase: ')

saida = ''
for caracter in frase:
    if caracter != ' ':
        saida = saida + caracter

print(saida)

"""## Questão 3

Faça um programa que leia uma frase e a exiba toda em letras maiúsculas.
"""

frase = input('Frase: ')

saida = frase.upper()

print(saida)

"""##Questão 4

Faça um programa que leia uma frase e a exiba com a inicial de cada palavra em maiúsculo.
"""

frase = input('Frase: ')

saida = frase.title()

print(saida)

#Versão sem o uso da função title()

frase = input('Frase: ')
tam = len(frase)

if tam > 0:
    saida = frase[0].upper()

for i in range(1,tam):
    if frase[i-1] == ' ':
        saida = saida + frase[i].upper()
    else:
        saida = saida + frase[i]

print(saida)

"""##Questão 5

Faça um programa que leia uma frase e a exiba com uma letra em cada linha.
"""

frase = input('Frase: ' )

tam = len(frase)

for i in range(tam):
    print(frase[i])

#Versão usando a string como objeto iterável do for

frase = input('Frase: ' )

for caracter in frase:
    print(caracter)

"""##Questão 6

Faça um programa que leia uma frase e a exiba invertida.
"""

frase = input('Frase: ')

tam = len(frase)

print('\nFrase invertida:')
for i in range(tam-1,-1,-1):
    print(frase[i],end='')

#VERSÃO USANDO FATIAMENTO

frase = input('Frase: ')
tam = len(frase)
saida = frase[::-1]
print('\nFrase invertida:')
print(saida)