# -*- coding: utf-8 -*-
"""APE 2022.1 - Lista Resolvida - Vetor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ejDnjryqd11qmso_hzalIqT-wWMQQy8p

**IFPB - CAMPUS JOÃO PESSOA    
CURSO: SISTEMAS PARA INTERNET     
DISCIPLINA: ALGORITMOS E PROGRAMAÇÃO ESTRUTURADA     
PROFESSORES: CANDIDO EGYPTO / EDEMBERG ROCHA**

# LISTA DE EXERCÍCIOS (RESOLVIDA) - VETOR

##Questão 1

Escreva um programa que leia um vetor A de N números inteiros (N será lido) e um outro inteiro K, construa e exiba um outro vetor B cujos elementos são os respectivos elementos de A multiplicados por K.     
Ex: A = [1,2,3], K = 5, B = [5,10,15].
"""

#leitura do tamanho do vetor
n = int(input('Digite o tamanho do vetor A: '))

#inicialização dos vetores A e B
a = [None]*n
b = [None]*n

#leitura do vetor A
print('Digite os elementos do vetor A:')
for i in range(n):
    a[i] = int(input(f'A[{i}]: '))

#leitura do valor K
k = int(input('Digite o valor de K: '))

#geração do vetor B
for i in range(n):
    b[i] = a[i] * k

#exibição dos resultados
print()
print('A =',a)
print('K =',k)
print('B =',b)

"""##Questão 2

Escreva um programa que leia um vetor V (contendo 30 inteiros) e um valor inteiro K, calcule e exiba a quantidade de ocorrências de K dentro de V.
"""

#testando com 5 ao invés de 30
n = 5  

#inicialização do vetor V
v = [None]*n

#leitura do vetor V
print('Digite os elementos do vetor A:')
for i in range(n):
    v[i] = int(input())

#leitura do valor K
k = int(input('Digite o valor de K: '))

#contagem das ocorrências
cont = 0
for e in v:
    if e == k:
        cont += 1

#exibição do resultado
print(f'\nNº de ocorrências: {cont}')

"""Versão com o vetor gerado com valores aleatórios"""

import random

n = 30  

#inicialização do vetor V
v = [None]*n

#geração aleatória do vetor V
for i in range(n):
    v[i] = random.randint(1,10)

#exibição do vetor V
print('V =',v)

#leitura do valor K
k = int(input('\nDigite o valor de K: '))

#contagem das ocorrências
cont = 0
for e in v:
    if e == k:
        cont += 1 

#exibição do resultado
print(f'\nNº de ocorrências: {cont}')

"""## Questão 3

Escreva um programa que leia um vetor V contendo N elementos inteiros (N será lido) e um valor inteiro K, verifique e exiba se o K está ou não no vetor.  Se estiver, informe em que posição (índice).      
Obs: K pode se repetir no vetor, nesse caso, mostre todas as posições onde o K aparece.
"""

#leitura do tamanho do vetor V
n = int(input('Digite o tamanho do vetor V: '))

#inicialização do vetor V
v = [None]*n

#leitura do vetor V
print('\nDigite os elementos do vetor A:')
for i in range(n):
    v[i] = int(input())

#leitura do valor K
k = int(input('\nDigite o valor de K: '))

#verificação se K está em V
existe = False
for e in v:
    if e == k:
        existe = True
        break

#exibição dos resultados
if existe:   # if existe == True:
    print(f'\nO valor {k} está no vetor nas seguintes posições:')
    for i in range(n):
        if v[i] == k:
            print(i)
else:
    print(f'\nO valor {k} não está no vetor')

"""##Questão 4

Escreva um programa que leia 10 números e armazene-os em um vetor.     
Exiba: 
* Os números que estão nos índices pares; 
* Os números que estão nos índices ímpares.
"""

# inicialização das variáveis
n = 10
numeros = [None]*n

# leitura dos números 
for i in range(n):
    numeros[i] = int(input(f'numero[{i}]: '))

# exibição dos números que estão nos índices pares
print('\nNúmeros que estão nos índices pares:')
for i in range(0,n,2):
    print(numeros[i])

# exibição dos números que estão nos índices ímpares
print('\nNúmeros que estão nos índices ímpares:')
for i in range(1,n,2):
    print(numeros[i])

"""Outra versão:"""

# inicialização das variáveis
n = 10
numeros = [None]*n

# leitura dos números 
for i in range(n):
    numeros[i] = int(input('numero[' + str(i) + ']: '))

# exibição dos números que estão nos índices pares
print('\nNúmeros que estão nos índices pares:')
for i in range(n):
    if i % 2 == 0:
        print(numeros[i])

# exibição dos números que estão nos índices ímpares
print('\nNúmeros que estão nos índices ímpares:')
for i in range(n):
    if i % 2 == 1:
        print(numeros[i])

"""##Questão 5

Escreva um programa que receba um vetor V de N números inteiros (N será lido), determine e exiba o maior e o menor elemento deste vetor e seus respectivos índices.      
Obs: suponha a inexistência de valores repetidos.
"""

# leitura do tamanho do vetor
n = int(input('Digite o tamanho do vetor: '))

# inicialização do vetor
v = [None]*n

# leitura dos elementos do vetor
print(f'Digite os {n} elementos do vetor:')
for i in range(n):
    v[i] = int(input())

# inicializando as variáveis com o valor e o índice do 1º elemento
maior = v[0]
indMa = 0
menor = v[0]
indMe = 0

# acessando do 2º ao último elemento do vetor  
for i in range(1,n):
    
    # testando o valor da vez com o atual maior
    if v[i] > maior: 
        maior = v[i]
        indMa = i

    # testando o valor da vez com o atual menor    
    if v[i] < menor: 
        menor = v[i]
        indMe = i

# exibição dos resultados
print(f'\nVetor = {v}')
print(f'\nMaior = {maior}')
print(f'Indice = {indMa}')
print(f'\nMenor = {menor}')
print(f'Indice = {indMe}')

"""Outra versão:"""

# leitura do tamanho do vetor
n = int(input('Digite o tamanho do vetor: '))

# inicialização do vetor
v = [None]*n

# leitura dos elementos do vetor
print(f'Digite os {n} elementos do vetor:')
for i in range(n):
    v[i] = int(input())

# inicializando as variáveis com o índice do 1º elemento (0)    
indMa = 0
indMe = 0

# acessando do 2º ao último elemento do vetor  
for i in range(1,n):

    # testando o valor da vez com o valor da atual posição do maior
    if v[i] > v[indMa]:
        indMa = i
    # testando o valor da vez com o valor da atual posição do menor
    if v[i] < v[indMe]:
        indMe = i

# exibição dos resultados
print(f'\nVetor = {v}')
print(f'\nMaior = {maior}')
print(f'Indice = {indMa}')
print(f'\nMenor = {menor}')
print(f'Indice = {indMe}')

"""##Questão 6

Escreva um programa que leia um vetor de N números inteiros (N será lido), inverta a ordem dos elementos do vetor e exiba o vetor invertido.     
Ex: V = [1, 3, 5, 7], após a inversão: V = [7, 5, 3, 1].      
Obs: É necessário inverter os elementos do vetor, não basta imprimi-los em ordem inversa!
"""

#leitura do tamanho do vetor
n = int(input('Digite o tamanho do vetor: '))

#inicialização do vetor
v = [None]*n

#leitura dos elementos do vetor
print(f'Digite os {n} elementos do vetor:')
for i in range(n):
    v[i] = int(input())

#exibição do vetor antes da inversão
print(f'\nAntes da inversão: {v}')

#inversão da ordem dos elementos do vetor
j = n-1
for i in range(n//2):
    aux = v[i]
    v[i] = v[j]
    v[j] = aux
    j = j-1

#exibição do vetor depois da inversão
print(f'\nDepois da inversão: {v}')