# -*- coding: utf-8 -*-
"""APE 2022.1 - Lista Resolvida - Estrutura de Repetição (complementar).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FMHbHfDiyoiRbB7pV2rPvlxbwKqrb082

**IFPB - CAMPUS JOÃO PESSOA    
CURSO: SISTEMAS PARA INTERNET     
DISCIPLINA: ALGORITMOS E PROGRAMAÇÃO ESTRUTURADA     
PROFESSORES: CANDIDO EGYPTO / EDEMBERG ROCHA**

# LISTA DE EXERCÍCIOS (RESOLVIDA) – ESTRUTURA DE REPETIÇÃO (COMPLEMENTAR)

##Questão 1

Faça um programa que leia um número N, calcule e mostre os N primeiros termos da sequência de Fibonacci (0, 1, 1, 2, 3, 5, 8, 13, ...).     
O valor lido para N sempre será maior ou igual a 2.
"""

n = int(input('Digite o número de termos desejado: '))
a = 0
b = 1

print('Sequência de Fibonacci:',a,b,end=' ')

for i in range (3,n+1):
    c = a + b
    print(c,end=' ')
    a = b
    b = c

"""##Questão 2

Um número é, por definição, primo se ele não tem divisores, exceto 1 e ele próprio.    
Faça um programa que mostre todos os números primos de 1 a N (obs: N será lido).
"""

n = int(input('Digite o valor de N: '))

for i in range(1,n+1):
    primo = True
    for j in range(2,i):
        if i % j == 0:
            primo = False
            break
    if primo:
        print(i,end=' ')

"""## Questão 3

O algoritmo de Euclides para determinar o MDC entre dois números inteiros consiste em formar uma sequência de inteiros cujos dois primeiros elementos são os números dados.     
Cada elemento seguinte é o resto da divisão dos dois anteriores.     
A sequência terminará quando um elemento da mesma for nulo.     
O MDC entre os números dados é o elemento anterior ao zero.     
Faça uma implementação deste programa.      
Ex: Dados os números 12 e 15, será formada a sequência: 12, 15, 12, 3, 0 e o MDC entre 12 e 15 é 3.
"""

a = int(input('Digite o 1º número: '))
b = int(input('Digite o 2º número: '))

print('\nSequência:',a,b,end=' ')

while True:

    c = a % b
    print(c,end=' ')

    if c == 0:
        break

    a = b
    b = c

print(f'\nMDC = {b}')

"""##Questão 4

Um dado material radioativo perde metade de sua massa a cada 50 segundos.    
Faça um programa que leia uma certa quantidade de massa, em gramas, deste material e imprima o tempo necessário para que sua massa se torne menor que 0.5g.
"""

tempo = 0

massa = float(input('Informe a quantidade de massa (em gramas): '))

while massa >= 0.5:
    tempo += 50  # tempo = tempo + 50
    massa /= 2   # massa = massa / 2

print(f'Tempo = {tempo} segundos')

"""##Questão 5

Faça um programa que, leia a temperatura dos 30 dias do mês de abril diga qual o dia mais quente e o dia mais frio do mês.     
Obs: suponha que não haja empates.
"""

ndias = 3  # coloquei um valor menor para fins de teste
temp_quente = -100
temp_frio = 100

for dia in range(1,ndias+1):
    
    temp = int(input('Temperatura do dia '+ str(dia) + ': '))
    
    if temp > temp_quente:
        temp_quente = temp
        dia_quente = dia
    
    if temp < temp_frio:
        temp_frio = temp
        dia_frio = dia

print()
print(f'Mais quente: dia {dia_quente}, com {temp_quente} graus.')
print(f'Mais frio  : dia {dia_frio}, com {temp_frio} graus.')

"""##Questão 6

Faça um programa que solicite ao usuário uma senha.     
Caso a senha digitada esteja correta, o programa deverá mostrar senha correta.     
Caso contrário, o programa deverá mostrar senha incorreta e pedir para o usuário tentar novamente digitar a senha correta.      
Mas, se o usuário fornecer três senhas incorretas, o programa deverá encerrar a sua execução.     
(Obs: a senha correta é “abcd”).
"""

correta = 'abcd'
n = 0

while True:

    senha = input('Digite a senha: ')
    n += 1

    if senha == correta:
        print('Senha correta!')
        break

    print('Senha incorreta!',end=' ')

    if n >= 3:
        print('Nº de tentativas excedido.')
        break

    print('Tente novamente...\n')

"""##Questão 7

Uma certa empresa pretende verificar se os seus empregados estarão qualificados ou não para aposentadoria em 2022.       
Para estar em condições, um dos seguintes requisitos deve ser satisfeito:
*	Ter no mínimo 65 anos de idade; ou
*	Ter trabalhado no mínimo 30 anos; ou
*	Ter no mínimo 60 anos e ter trabalhado no mínimo 25 anos.     

Com base nas informações acima, faça um programa para:    
*	Ler o nome do empregado, o ano de nascimento e o ano de seu ingresso na empresa. 
*	Calcular e exibir a idade e o tempo de trabalho do empregado (estimado ao final de 2021) 
*	Exibir a mensagem “Pode Requerer Aposentadoria” se atender aos requisitos ou “Não Pode Requerer Aposentadoria” caso contrário.     

Ao final de cada execução, o programa deverá perguntar se o usuário deseja fazer nova verificação. Se sim, o programa deverá repetir tudo novamente, caso contrário deverá encerrar.
"""

anoref = 2021

while True:
    
    nome = input('Nome: ')
    nasc = int(input('Ano de nascimento: '))
    ingr = int(input('Ano de ingresso na empresa: '))
    
    idade = anoref - nasc
    tempo = anoref - ingr
    
    print(f'\nIdade: {idade} anos')
    print(f'Tempo de trabalho: {tempo} anos')
    
    if idade >= 65 or tempo >= 30 or (idade >= 60 and tempo >= 25):
        print('Pode Requerer Aposentadoria')
    else:
        print('Não Pode Requerer Aposentadoria')
    
    if input('\nDeseja fazer nova verificação (s/n)? ').lower() == 'n':
        break
    
    print()

"""##Questão 8

Faça um programa que acompanhe um set de uma partida de vôlei.     
O programa deve ler o código da equipe (A ou B) que ganhou o ponto e responder quem ganha a partida.     
O set chega ao final se uma das equipes chega a 25 pontos e a diferença de pontos entre elas é maior ou igual a dois.     
A equipe que conseguir isso é a vencedora do set.
"""

pa = 0
pb = 0
fim = 3 #pontuação final do set (colocado valor menor para fins de teste)

while True:

    equipe = input('Informe o código da equipe que ganhou o ponto (A ou B): ').upper()

    if equipe == 'A':
        pa += 1
    else:
        pb += 1

    print(f'Placar: A {pa} x {pb} B\n')

    if pa > pb:
        dif = pa - pb
    else:
        dif = pb - pa

    if (pa >= fim or pb >= fim) and (dif >= 2):
        break

if pa > pb:
    print('A Equipe A foi a vencedora')
else:
    print('A Equipe B foi a vencedora')